# Generated by Django 2.1.5 on 2019-04-06 16:19

import analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='result',
            field=models.CharField(choices=[(analyzer.models.AnalysisResult('Nothing malicious found'), 'Nothing malicious found'), (analyzer.models.AnalysisResult('Malicious indicators found'), 'Malicious indicators found'), (analyzer.models.AnalysisResult('Error during analysis'), 'Error during analysis')], max_length=25),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[(analyzer.models.AnalysisStatus('Upload in progress'), 'Upload in progress'), (analyzer.models.AnalysisStatus('Extraction of indicator'), 'Extraction of indicator'), (analyzer.models.AnalysisStatus('Research of indicators in the database'), 'Research of indicators in the database'), (analyzer.models.AnalysisStatus('Error'), 'Error'), (analyzer.models.AnalysisStatus('Done'), 'Done')], max_length=25),
        ),
    ]
